apiVersion: v1
kind: Pod
metadata:
  name: aws-debug-eks
  namespace: mediconnect-staging
spec:
  serviceAccountName: mediconnect-sa
  containers:
  - name: aws-debug-eks
    image: amazon/aws-cli
    command: ["sleep", "3600"]
    env:
    - name: AWS_REGION
      value: "eu-central-1"
