apiVersion: v1
kind: Namespace
metadata:
  name: mediconnect-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: mediconnect-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: mediconnect-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mediconnect-sa
  namespace: mediconnect-staging
  labels:
    azure.workload.identity/use: "true" 
  annotations:
    azure.workload.identity/client-id: "__AZURE_CLIENT_ID__"
    eks.amazonaws.com/role-arn: "__AWS_ROLE_ARN__"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mediconnect-sa
  namespace: mediconnect-prod
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "__AZURE_CLIENT_ID__"
    eks.amazonaws.com/role-arn: "__AWS_ROLE_ARN__"