apiVersion: v1
kind: Namespace
metadata:
  name: mediconnect-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: mediconnect-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: mediconnect-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mediconnect-sa
  namespace: mediconnect-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mediconnect-sa
  namespace: mediconnect-prod